[package]
name = "esticc"
version = "0.3.2"
description = "ESTICC - Panel de Seguridad Local"
authors = ["yeagob556"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["sync"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
